server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false

spring:
  liquibase:
    enabled: true
  application:
    name: db2
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://postgres:5432/shipping
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        format_sql: true
        show-sql: true
  output:
    ansi:
      enabled: always